# Source: https://contentlab.io/postgresql-on-kubernetes/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-postgres-db
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: my-postgres-db
  serviceName: my-postgres-service
  replicas: 1
  template:
    metadata:
      labels:
        app: my-postgres-db
    spec:
      containers:
        - name: my-postgres-db
          image: postgres
          volumeMounts:
            - name: postgres-disk
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
  volumeClaimTemplates:
    - metadata:
        name: postgres-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi