# API Best Practices

- Versioning
- Security
	- Spike Arrest
	- IP Whitelisting
	- CSRF
	- Authentication and Authorization
		- OAuth2
			- Grant types
				- Client Credentials
				- Authorization Code
				- Implicit
				- Password
			- Scope
			- Expiry Time
			- Access Token, Refresh Token, ID Token	
		- Basic Auth
		- API Key
- Open API Specification (Swagger)
- Logging
- HATEOS
- Analytics